### ISSUE TITLE
new fields in the V2 API - and one in V1

### ISSUE THREAD

**Issue by scaspers** [scaspers/D3-API#10] opened 2017-07-10 02:53 UTC
In the process of doing the v2 additions I broke the orderStatus in v1.... it is now an object.

*** NEW for v1 ***
"orderStatus": {
. . . . "statusCode": Integer,
. . . . "statusDesc": String,
. . . . "statusTimestamp": integer (timestamp),
. . . . "statusMisc": String
}

*** NEW for v2 ***
"serviceAdvisor": String
"billingSummary": String[]
"totalBill": String

If you want you can add these all then I will copy v2 config to v1.

Sorry about the breakage. :)

**Comment by DanielCaspers** [comment] 2017-07-11 04:46
I have a work in progress pushed to Nightly B that points to V2 and includes the 3 new properties shown. Please check it out.

Also, please look for a regression on your end regarding file locking. I am getting HTTP 428s right after requesting a lock on attempting to save new data. I don't want to close this issue until we fix the model binding issues AND ensure we don't have any regressions.

**Comment by scaspers** [comment] 2017-07-11 15:06
I fix the API versioning on the PUT's.  The API was returning v1 data for all PUT's which was breaking at the response.   There may still be another issue with the 428 error but I cannot replicate.   Maybe you can test some more too.

**Comment by DanielCaspers** [comment] 2017-07-12 03:44
I was unable to reproduce the HTTP 428 issue. I think we're done here :) Reopen if I closed in error.

**Closed by DanielCaspers** 2017-07-12 03:44 UTC
Labels: blocker
